commercetools/commercetools-php-sdk

- src/Client.php
- src/Request/AbstractApiRequest.php
- src/Request/ClientRequestInterface.php
- tests/unit/ClientTest.php
- tests/unit/Request/AbstractApiRequestTest.php
> add concurrent batch call for api client

- docroot/annotations.php
- docroot/index.php
- src/Client.php
- src/Error/Message.php
- src/Model/Common/Reference.php
- src/Request/AbstractApiRequest.php
- src/Request/ClientRequestInterface.php
- src/Response/AbstractApiResponse.php
- src/Response/ApiResponseInterface.php
- src/Response/PagedQueryResponse.php
- src/Response/PagedSearchResponse.php
- tests/unit/ClientTest.php
- tests/unit/ConfigTest.php
- tests/unit/Model/Common/ReferenceTest.php
- tests/unit/Response/AbstractApiResponseTest.php
- tests/unit/Response/PagedSearchResponseTest.php
> add future requests

- features/request/TaxCategory/TaxCategoryCreate.feature
- src/Model/Common/TaxPortion.php
- src/Model/TaxCategory/TaxCategoryDraft.php
- src/Model/TaxCategory/TaxRateCollection.php
- src/Request/Products/ProductProjectionFetchBySkuRequest.php
- src/Request/States/StateCreateRequest.php
- src/Request/TaxCategories/TaxCategoryCreateRequest.php
- tests/unit/Request/TaxCategories/TaxCategoryCreateRequestTest.php
> add create tax category request

- features/request/CustomerGroup/CustomerGroupCreate.feature
- src/Model/CustomerGroup/CustomerGroupDraft.php
- src/Request/CustomerGroups/CustomerGroupCreateRequest.php
- tests/unit/Request/CustomerGroups/CustomerGroupCreateRequestTest.php
> add CustomerGroupCreateRequest

- features/request/Channel/ChannelCreate.feature
- features/request/TaxCategory/TaxCategoryCreate.feature
- features/request/Zone/ZoneCreate.feature
- src/Model/Channel/ChannelDraft.php
- src/Request/Channels/ChannelCreateRequest.php
- tests/unit/Request/Channels/ChannelCreateRequestTest.php
> add ChannelCreateRequest

- features/request/ShippingMethod/ShippingMethodCreate.feature
- src/Model/ShippingMethod/ShippingMethodCollection.php
- src/Model/ShippingMethod/ShippingMethodDraft.php
- src/Request/ShippingMethods/ShippingMethodCreateRequest.php
- src/Request/ShippingMethods/ShippingMethodFetchByIdRequest.php
- src/Request/ShippingMethods/ShippingMethodUpdateRequest.php
- src/Request/ShippingMethods/ShippingMethodsQueryRequest.php
- tests/unit/Request/GenericFetchByIdRequestTest.php
- tests/unit/Request/GenericQueryRequestTest.php
- tests/unit/Request/GenericUpdateRequestTest.php
- tests/unit/Request/ShippingMethods/ShippingMethodCreateRequestTest.php
> add ShippingMethodCreateRequest

- features/request/ProductType/ProductTypeCreate.feature
- src/Model/Common/ContextTrait.php
- src/Model/ProductType/AttributeType.php
- src/Request/ProductTypes/ProductTypeCreateRequest.php
- tests/unit/Model/Common/ContextTest.php
- tests/unit/Model/Common/JsonObjectTest.php
- tests/unit/Model/ProductType/AttributeTypeTest.php
- tests/unit/Request/ProductTypes/ProductTypeCreateRequestTest.php
> add ProductTypeCreateRequest

- features/request/ProductDiscount/ProductDiscountCreate.feature
- src/Model/ProductDiscount/ProductDiscountDraft.php
- src/Request/ProductDiscounts/ProductDiscountCreateRequest.php
- tests/unit/Request/ProductDiscounts/ProductDiscountCreateRequestTest.php
> add ProductDiscountCreateRequest

- features/request/Product/ProductUpdate.feature
- src/Model/Common/Price.php
- src/Model/Message/Message.php
- src/Request/Products/Command/ProductChangePriceAction.php
- src/Request/Products/Command/ProductRemovePriceAction.php
- src/Request/Products/ProductsSearchRequest.php
- src/Response/ApiResponseInterface.php
- tests/fixtures/models.yaml
- tests/unit/Request/GenericActionTest.php
> [BREAKING] update price update and remove action to priceId

- features/request/Product/ProductUpdate.feature
- src/Model/Common/Price.php
- tests/fixtures/models.yaml
> add price validity ranges

- src/Request/Reviews/ReviewDeleteRequest.php
> feat(Reviews): add review delete request

- src/Model/Message/CustomLineItemStateTransitionMessage.php
- src/Model/Message/DeliveryAddedMessage.php
- src/Model/Message/LineItemStateTransitionMessage.php
- src/Model/Message/Message.php
- src/Model/Message/OrderCreatedMessage.php
- src/Model/Message/OrderImportedMessage.php
- src/Model/Message/OrderStateChangedMessage.php
- src/Model/Message/ParcelAddedToDeliveryMessage.php
- src/Model/Message/ProductPublishedMessage.php
- src/Model/Message/ProductUnpublishedMessage.php
- src/Model/Type/FieldType.php
- src/Request/CustomField/Command/SetCustomFieldAction.php
- src/Request/Products/Command/ProductSetAttributeAction.php
- src/Request/Products/Command/ProductSetAttributeInAllVariantsAction.php
> feat(Message): add specific message objects

- .travis.yml
- composer.json
- src/Cache/ApcuCacheAdapter.php
- src/Cache/CacheAdapterFactory.php
- tests/unit/Cache/ApcCacheAdapterTest.php
- tests/unit/Cache/CacheAdapterFactoryTest.php
- tests/unit/Cache/DoctrineCacheAdapterTest.php
- tests/unit/Client/OAuth/ManagerTest.php
> Feature js hhvm fixes

- src/AbstractHttpClient.php
- src/Client.php
- src/Client/Adapter/AdapterFactory.php
- src/Client/Adapter/AdapterInterface.php
- src/Client/Adapter/Guzzle5Adapter.php
- src/Client/Adapter/Guzzle6Adapter.php
> Feature js httpfactory issue #229

- src/Model/Common/Asset.php
- src/Model/Common/AssetCollection.php
- src/Model/Common/AssetDimension.php
- src/Model/Common/AssetDraft.php
- src/Model/Common/AssetDraftCollection.php
- src/Model/Common/AssetSource.php
- src/Model/Common/AssetSourceCollection.php
- src/Model/Product/ProductVariant.php
- src/Model/Product/ProductVariantDraft.php
- src/Request/Products/Command/ProductAddAssetAction.php
- src/Request/Products/Command/ProductChangeAssetNameAction.php
- src/Request/Products/Command/ProductChangeAssetOrderAction.php
- src/Request/Products/Command/ProductRemoveAssetAction.php
- src/Request/Products/Command/ProductSetAssetCustomFieldAction.php
- src/Request/Products/Command/ProductSetAssetCustomTypeAction.php
- src/Request/Products/Command/ProductSetAssetDescriptionAction.php
- src/Request/Products/Command/ProductSetAssetSourcesAction.php
- src/Request/Products/Command/ProductSetAssetTagsAction.php
- tests/fixtures/models.yaml
- tests/integration/Product/ProductUpdateRequestTest.php
> Feature js assets #241

- .travis.yml
- src/Model/Category/Category.php
- src/Model/Category/CategoryDraft.php
- src/Request/Categories/Command/CategoryAddAssetAction.php
- src/Request/Categories/Command/CategoryChangeAssetNameAction.php
- src/Request/Categories/Command/CategoryChangeAssetOrderAction.php
- src/Request/Categories/Command/CategoryRemoveAssetAction.php
- src/Request/Categories/Command/CategorySetAssetCustomFieldAction.php
- src/Request/Categories/Command/CategorySetAssetCustomTypeAction.php
- src/Request/Categories/Command/CategorySetAssetDescriptionAction.php
- src/Request/Categories/Command/CategorySetAssetSourcesAction.php
- src/Request/Categories/Command/CategorySetAssetTagsAction.php
- src/Request/Products/Command/ProductAddAssetAction.php
- tests/fixtures/models.yaml
- tests/integration/Category/CategoryUpdateRequestTest.php
> Feature js category assets

- README.md
- composer.json
- set_guzzle5.sh
- src/Client.php
- src/Client/Adapter/AdapterInterface.php
- src/Client/Adapter/Guzzle5Adapter.php
- src/Client/Adapter/Guzzle6Adapter.php
- src/Config.php
- src/Helper/Subscriber/Log/Formatter.php
- src/Helper/Subscriber/Log/LogSubscriber.php
- src/Helper/Subscriber/Log/SimpleLogger.php
- tests/unit/ClientTest.php
> feat(Client): add logLevel configuration option

- src/Model/Common/Collection.php
- src/Model/Product/FacetResultCollection.php
- src/Model/Product/LocalizedSearchKeywords.php
- src/Model/Product/LocalizedSuggestionCollection.php
- tests/unit/Model/Common/CollectionTest.php
- tests/unit/Model/Product/LocalizedSearchKeywordsTest.php
> fix(Collection): fix iterator for unset elements of collections

- composer.json
- src/Core/Client.php
- src/Core/Client/Adapter/CorrelationIdAdapter.php
- src/Core/Client/Adapter/CorrelationIdAware.php
- src/Core/Client/Adapter/Guzzle5Adapter.php
- src/Core/Client/Adapter/Guzzle6Adapter.php
- src/Core/Client/OAuth/Manager.php
- src/Core/Config.php
- src/Core/Helper/CorrelationIdProvider.php
- src/Core/Helper/DefaultCorrelationIdProvider.php
- src/Core/Helper/Subscriber/CorrelationIdSubscriber.php
- tests/integration/ClientTest.php
- tests/integration/ManagerTest.php
- tests/integration/Project/ProjectGetRequestTest.php
- tests/myapp.yml.dist
> Add correlationId provider

- src/Core/Client.php
- src/Core/Client/Adapter/AdapterOptionInterface.php
- src/Core/Client/Adapter/Guzzle5Adapter.php
- src/Core/Client/Adapter/Guzzle6Adapter.php
- src/Core/Config.php
- tests/unit/ClientTest.php
> feat(Client): add configuration options for guzzle

- src/Core/Request/CustomObjects/CustomObjectByIdGetRequest.php
- tests/integration/CustomObject/CustomObjectQueryRequestTest.php
- tests/unit/Request/GenericByIdGetRequestTest.php
Added a CustomObjectByIdGetRequest class & updated the integration/unit tests.
> added CustomObjectByIdGetRequest + tests

- .scrutinizer.yml
> chore(scrutinizer): use new analysis engine

- .gitignore
- src/Core/Model/Message/DeliveryItemsUpdatedMessage.php
- src/Core/Model/Message/DeliveryRemovedMessage.php
- src/Core/Model/Message/ParcelItemsUpdatedMessage.php
- src/Core/Model/Message/ParcelMeasurementsUpdatedMessage.php
- src/Core/Model/Message/ParcelRemovedFromDeliveryMessage.php
- src/Core/Model/Message/ParcelTrackingDataUpdatedMessage.php
- src/Core/Request/ProductTypes/Command/ProductTypeRemoveEnumValuesAction.php
- tests/integration/ProductType/ProductTypeUpdateRequestTest.php
> feat(ProductType): support product type removeEnumValues update action

- src/Core/Model/Common/AttributeCollection.php
- src/Core/Model/Common/JsonObject.php
- tests/unit/Model/Common/AttributeCollectionTest.php
- tests/unit/Model/Common/JsonObjectTest.php
> Enhance JsonObject and Collection element getter

- src/Core/Builder/Update/CartDiscountsActionBuilder.php
- src/Core/Builder/Update/CartsActionBuilder.php
- src/Core/Builder/Update/CategoriesActionBuilder.php
- src/Core/Builder/Update/ChannelsActionBuilder.php
- src/Core/Builder/Update/CustomerGroupsActionBuilder.php
- src/Core/Builder/Update/CustomersActionBuilder.php
- src/Core/Builder/Update/DiscountCodesActionBuilder.php
- src/Core/Builder/Update/InventoryActionBuilder.php
- src/Core/Builder/Update/OrdersActionBuilder.php
- src/Core/Builder/Update/ReviewsActionBuilder.php
- src/Core/Request/CartDiscounts/Command/CartDiscountSetCustomFieldAction.php
- src/Core/Request/CartDiscounts/Command/CartDiscountSetCustomTypeAction.php
- src/Core/Request/Carts/Command/CartSetCustomFieldAction.php
- src/Core/Request/Carts/Command/CartSetCustomTypeAction.php
- src/Core/Request/Categories/Command/CategorySetCustomFieldAction.php
- src/Core/Request/Categories/Command/CategorySetCustomTypeAction.php
- src/Core/Request/Channels/Command/ChannelSetCustomFieldAction.php
- src/Core/Request/Channels/Command/ChannelSetCustomTypeAction.php
- src/Core/Request/CustomerGroups/Command/CustomerGroupSetCustomFieldAction.php
- src/Core/Request/CustomerGroups/Command/CustomerGroupSetCustomTypeAction.php
- src/Core/Request/Customers/Command/CustomerSetCustomFieldAction.php
- src/Core/Request/Customers/Command/CustomerSetCustomTypeAction.php
- src/Core/Request/DiscountCodes/Command/DiscountCodeSetCustomFieldAction.php
- src/Core/Request/DiscountCodes/Command/DiscountCodeSetCustomTypeAction.php
- src/Core/Request/Inventory/Command/InventorySetCustomFieldAction.php
- src/Core/Request/Inventory/Command/InventorySetCustomTypeAction.php
- src/Core/Request/Orders/Command/OrderSetCustomFieldAction.php
- src/Core/Request/Orders/Command/OrderSetCustomTypeAction.php
- src/Core/Request/Reviews/Command/ReviewSetCustomFieldAction.php
- src/Core/Request/Reviews/Command/ReviewSetCustomTypeAction.php
> feat(RequestBuilder): add SetCustomTypeActions at Customer, Cart, Order

- src/Core/Builder/Update/ShoppingListsActionBuilder.php
- src/Core/Model/ShoppingList/ShoppingList.php
- src/Core/Model/ShoppingList/ShoppingListDraft.php
- src/Core/Request/ShoppingLists/Command/ShoppingListSetAnonymousIdAction.php
> feat(ShoppingList): support AnonymousId on ShoppingList owner

- README.md
> docs(Readme): update readme

- src/Core/Request/Carts/CartDeleteRequest.php
- src/Core/Request/CustomObjects/CustomObjectDeleteByKeyRequest.php
- src/Core/Request/CustomObjects/CustomObjectDeleteRequest.php
- src/Core/Request/Customers/CustomerDeleteByKeyRequest.php
- src/Core/Request/Customers/CustomerDeleteRequest.php
- src/Core/Request/DataErasureTrait.php
- src/Core/Request/DiscountCodes/DiscountCodeDeleteRequest.php
- src/Core/Request/Orders/OrderDeleteByOrderNumberRequest.php
- src/Core/Request/Orders/OrderDeleteRequest.php
- src/Core/Request/Payments/PaymentDeleteByKeyRequest.php
- src/Core/Request/Payments/PaymentDeleteRequest.php
- src/Core/Request/Reviews/ReviewDeleteByKeyRequest.php
- src/Core/Request/Reviews/ReviewDeleteRequest.php
- src/Core/Request/ShoppingLists/ShoppingListDeleteByKeyRequest.php
- src/Core/Request/ShoppingLists/ShoppingListDeleteRequest.php
- tests/unit/DataErasureTest.php
> feat(Request): add GDPR dataErasure flag

- src/Core/Builder/Update/ProductDiscountsActionBuilder.php
- src/Core/Request/ProductDiscounts/Command/ProductDiscountSetValidFromAndUntilAction.php
- tests/integration/ProductDiscount/ProductDiscountUpdateRequestTest.php
> feat(ProductDiscount): add setValidFromAndUntil update action

- src/Core/Builder/Request/ProductDiscountRequestBuilder.php
- src/Core/Error/NoMatchingProductDiscountFoundError.php
- src/Core/Request/ProductDiscounts/ProductDiscountMatchingRequest.php
- tests/integration/ApiTestCase.php
- tests/integration/ProductDiscount/ProductDiscountMatchingRequestTest.php
- tests/integration/ProductDiscount/ProductDiscountQueryRequestTest.php
- tests/unit/Request/ProductDiscounts/ProductDiscountMatchingRequestTest.php
> feat(ProductDiscounts): add endpoint for Matching ProductDiscount

- src/Core/Builder/Request/CartDiscountRequestBuilder.php
- src/Core/Builder/Request/CartRequestBuilder.php
- src/Core/Builder/Request/CategoryRequestBuilder.php
- src/Core/Builder/Request/ChannelRequestBuilder.php
- src/Core/Builder/Request/CustomObjectRequestBuilder.php
- src/Core/Builder/Request/CustomerGroupRequestBuilder.php
- src/Core/Builder/Request/CustomerRequestBuilder.php
- src/Core/Builder/Request/DiscountCodeRequestBuilder.php
- src/Core/Builder/Request/GraphQLRequestBuilder.php
- src/Core/Builder/Request/InventoryRequestBuilder.php
- src/Core/Builder/Request/MessageRequestBuilder.php
- src/Core/Builder/Request/OrderRequestBuilder.php
- src/Core/Builder/Request/PaymentRequestBuilder.php
- src/Core/Builder/Request/ProductDiscountRequestBuilder.php
- src/Core/Builder/Request/ProductProjectionRequestBuilder.php
- src/Core/Builder/Request/ProductRequestBuilder.php
- src/Core/Builder/Request/ProductTypeRequestBuilder.php
- src/Core/Builder/Request/ProjectRequestBuilder.php
- src/Core/Builder/Request/ReviewRequestBuilder.php
- src/Core/Builder/Request/ShippingMethodRequestBuilder.php
- src/Core/Builder/Request/ShoppingListRequestBuilder.php
- src/Core/Builder/Request/StateRequestBuilder.php
- src/Core/Builder/Request/SubscriptionRequestBuilder.php
- src/Core/Builder/Request/TaxCategoryRequestBuilder.php
- src/Core/Builder/Request/TypeRequestBuilder.php
- src/Core/Builder/Request/ZoneRequestBuilder.php
- src/Core/Helper/Annotate/AnnotationGenerator.php
> Builder generator

- src/Core/Builder/Update/PaymentsActionBuilder.php
- src/Core/Model/Payment/Payment.php
- src/Core/Model/Payment/PaymentDraft.php
- src/Core/Request/Payments/Command/PaymentSetAnonymousIdAction.php
- tests/integration/Payment/PaymentUpdateRequestTest.php
> feat(Payment): support anonymousId

- bin/ctp-tlscheck.php
> fix(tls-check): update urls for TLS 1.2 check

- src/Core/Model/OrderEdit/OrderEditDraft.php
- tests/integration/ApiTestCase.php
- tests/integration/Cart/CartUpdateRequestTest.php
- tests/integration/DiscountCode/DiscountCodeQueryRequestTest.php
- tests/integration/Errors/ErrorResponseTest.php
- tests/integration/Me/MeRequestTest.php
- tests/integration/Order/OrderQueryRequestTest.php
- tests/integration/OrderEdit/OrderEditUpdateRequestTest.php
- tests/integration/Product/ProductImageUploadRequestTest.php
- tests/integration/Product/ProductUpdateRequestTest.php
- tests/integration/TestHelper.php
> refactor(TestHelper): refactor ApiTestCase

- .travis.yml
- set_guzzle5.sh
- src/Core/Model/Order/ReturnItem.php
> Update travis config

- README.md
- src/Core/Builder/Request/ApiClientRequestBuilder.php
- src/Core/Builder/Request/RequestBuilder.php
- src/Core/Helper/Annotate/AnnotationGenerator.php
- src/Core/Model/ApiClient/ApiClient.php
- src/Core/Model/ApiClient/ApiClientCollection.php
- src/Core/Model/ApiClient/ApiClientDraft.php
- src/Core/Request/ApiClients/ApiClientByIdGetRequest.php
- src/Core/Request/ApiClients/ApiClientCreateRequest.php
- src/Core/Request/ApiClients/ApiClientDeleteRequest.php
- src/Core/Request/ApiClients/ApiClientQueryRequest.php
- src/Core/Request/ApiClients/ApiClientsEndpoint.php
- tests/integration/ApiClient/ApiClientTest.php
- tests/unit/Request/GenericQueryRequestTest.php
> Api clients

- src/Core/Builder/Update/OrdersActionBuilder.php
- src/Core/Model/Message/OrderCustomerSetMessage.php
- src/Core/Request/Orders/Command/OrderSetCustomerIdAction.php
- tests/integration/Order/OrderUpdateRequestTest.php
> feat(Order): support setCustomerId

- src/Core/Model/Subscription/IronMQDestination.php
- src/Core/Model/Subscription/Subscription.php
> feat(Subscription): add subscription status

- src/Core/Builder/Update/SubscriptionsActionBuilder.php
- src/Core/Request/Subscriptions/Command/SubscriptionChangeDestinationAction.php
> feat(Subscription): add changeDestination update action

- src/Core/Request/ShippingMethods/ShippingMethodByCartIdGetRequest.php
- src/Core/Request/ShippingMethods/ShippingMethodByLocationGetRequest.php
- tests/integration/ShippingMethod/ShippingMethodQueryRequestTest.php
> feat(ShippingMethod): support Reference expansion

- src/Core/Model/Message/OrderDeletedMessage.php
> feat(Message): add OrderDeleted Message

- src/Core/Builder/Update/CartDiscountsActionBuilder.php
- src/Core/Builder/Update/DiscountCodesActionBuilder.php
- src/Core/Request/CartDiscounts/Command/CartDiscountSetValidFromAndUntilAction.php
- src/Core/Request/DiscountCodes/Command/DiscountCodeSetValidFromAndUntilAction.php
- tests/integration/CartDiscount/CartDiscountUpdateRequestTest.php
- tests/integration/DiscountCode/DiscountCodeUpdateRequestTest.php
- tests/integration/ProductDiscount/ProductDiscountUpdateRequestTest.php
> feat(Discounts): add setValidFromAndUntil action

- src/Core/Error/DiscountCodeNonApplicableError.php
- src/Core/Error/DuplicateFieldWithConflictingResourceError.php
- src/Core/Error/EnumValueIsUsedError.php
- src/Core/Error/MatchingPriceNotFoundError.php
- src/Core/Error/MissingTaxRateForCountryError.php
> feat(Error): add error codes for BadRequest

- src/Core/Model/Message/ProductPriceDiscountsSetMessage.php
- src/Core/Model/Message/ProductPriceDiscountsSetUpdatedPrice.php
- src/Core/Model/Message/ProductPriceDiscountsSetUpdatedPriceCollection.php
- src/Core/Model/Message/ProductPriceExternalDiscountSetMessage.php
> feat(Message): add new messages for ProductPriceDiscounts

- src/Core/Builder/Update/ProjectActionBuilder.php
- src/Core/Model/Message/MessagesConfiguration.php
- src/Core/Model/Message/MessagesConfigurationDraft.php
- src/Core/Request/Project/Command/ProjectChangeMessagesConfigurationAction.php
- src/Core/Request/Project/Command/ProjectChangeMessagesEnabledAction.php
- tests/integration/Project/ProjectUpdateRequestTest.php
- tests/unit/Model/RamlModelTest.php
> feat(Message): set MessagesConfiguration at Project

- src/Core/Request/Customers/CustomerPasswordTokenRequest.php
- tests/integration/Customer/CustomerLoginRequestTest.php
- tests/unit/Request/Customers/CustomerPasswordTokenRequestTest.php
> feat(PasswordResetToken): support ttlMinutes for token

- src/Core/Model/Order/LineItemImportDraft.php
> [WIP] - fix(LineItemImportDraft): add missing field distributionChannel

- src/Core/Builder/Request/ZoneRequestBuilder.php
- src/Core/Builder/Update/ZonesActionBuilder.php
- src/Core/Model/Zone/Zone.php
- src/Core/Model/Zone/ZoneDraft.php
- src/Core/Model/Zone/ZoneReference.php
- src/Core/Request/Zones/Command/ZoneSetKeyAction.php
- src/Core/Request/Zones/ZoneByKeyGetRequest.php
- src/Core/Request/Zones/ZoneDeleteByKeyRequest.php
- src/Core/Request/Zones/ZoneUpdateByKeyRequest.php
- tests/integration/Zone/ZoneQueryRequestTest.php
- tests/integration/Zone/ZoneUpdateRequestTest.php
> feat(Zone): support Key on shipping Zones

- tools/pre-commit.sh
> chore(pre-commit): PSR-2 verify only staged files and fix errors automatically

- src/Core/Builder/Update/ProductTypesActionBuilder.php
- src/Core/Request/ProductTypes/Command/ProductTypeChangeAttributeOrderByNameAction.php
- tests/integration/ProductType/ProductTypeUpdateRequestTest.php
> feat(ProductType): support changeAttributeOrderByName action

- src/Core/Request/Products/Command/ProductAddVariantAction.php
> feat(ProductAddVariantAction): support field assets

- src/Core/Model/TaxCategory/ExternalTaxRateDraft.php
- tests/integration/Cart/CartTaxModeTest.php
> feat(ExternalTaxRateDraft): add field includedInPrice

- composer.json
allow version 9.99 https://github.com/paragonie/random_compat#version-99999
> chore(random-compat): allow empty version 9.99

- .travis.yml
- src/Core/Client.php
- src/Core/Client/Adapter/Guzzle5Promise.php
- src/Core/Client/Adapter/Guzzle6Promise.php
- src/Core/Client/Adapter/PromiseGetInterface.php
- src/Core/Response/AbstractApiResponse.php
- src/Core/Response/ApiPromiseGetInterface.php
- tests/unit/ClientTest.php
> Get promise from guzzle response

- src/Core/Builder/Update/ExtensionsActionBuilder.php
- src/Core/Model/Extension/Extension.php
- src/Core/Model/Extension/ExtensionDraft.php
- src/Core/Request/Extensions/Command/ExtensionSetTimeoutInMsAction.php
- tests/integration/Extension/ExtensionUpdateRequestTest.php
> feat(Extension): support timeoutInMs

- src/Core/Model/Cart/Cart.php
- src/Core/Model/CartDiscount/CartDiscount.php
- src/Core/Model/Category/Category.php
- src/Core/Model/Channel/Channel.php
- src/Core/Model/Common/ClientLogging.php
- src/Core/Model/Common/CreatedBy.php
- src/Core/Model/Common/LastModifiedBy.php
- src/Core/Model/Customer/Customer.php
- src/Core/Model/CustomerGroup/CustomerGroup.php
- src/Core/Model/DiscountCode/DiscountCode.php
- src/Core/Model/Extension/Extension.php
- src/Core/Model/Inventory/InventoryEntry.php
- src/Core/Model/Order/Order.php
- src/Core/Model/OrderEdit/OrderEdit.php
- src/Core/Model/OrderEdit/StagedOrder.php
- src/Core/Model/Payment/Payment.php
- src/Core/Model/Product/Product.php
- src/Core/Model/ProductDiscount/ProductDiscount.php
- src/Core/Model/ProductType/ProductType.php
- src/Core/Model/Review/Review.php
- src/Core/Model/ShoppingList/ShoppingList.php
- src/Core/Model/State/State.php
- src/Core/Model/Subscription/Subscription.php
- src/Core/Model/TaxCategory/TaxCategory.php
- src/Core/Model/Type/Type.php
- src/Core/Request/AbstractApiRequest.php
- tests/integration/Customer/CustomerUpdateRequestTest.php
> Client logging

- src/Core/Builder/Request/CartDiscountRequestBuilder.php
- src/Core/Builder/Update/CartDiscountsActionBuilder.php
- src/Core/Model/CartDiscount/CartDiscount.php
- src/Core/Model/CartDiscount/CartDiscountDraft.php
- src/Core/Request/CartDiscounts/CartDiscountByKeyGetRequest.php
- src/Core/Request/CartDiscounts/CartDiscountDeleteByKeyRequest.php
- src/Core/Request/CartDiscounts/CartDiscountUpdateByKeyRequest.php
- src/Core/Request/CartDiscounts/Command/CartDiscountSetKeyAction.php
- tests/integration/CartDiscount/CartDiscountCreateRequestTest.php
- tests/integration/CartDiscount/CartDiscountQueryRequestTest.php
- tests/integration/CartDiscount/CartDiscountUpdateRequestTest.php
> feat(CartDiscount): support key attribute

- src/Core/Builder/Update/TypesActionBuilder.php
- src/Core/Request/Types/Command/TypeChangeEnumValueLabelAction.php
- src/Core/Request/Types/Command/TypeChangeInputHintAction.php
- src/Core/Request/Types/Command/TypeChangeLocalizedEnumValueLabelAction.php
- tests/integration/Type/TypeUpdateRequestTest.php
> feat(Type): add new type update actions

- src/Core/Builder/Request/ProductDiscountRequestBuilder.php
- src/Core/Builder/Update/ProductDiscountsActionBuilder.php
- src/Core/Model/ProductDiscount/ProductDiscount.php
- src/Core/Model/ProductDiscount/ProductDiscountDraft.php
- src/Core/Request/ProductDiscounts/Command/ProductDiscountSetKeyAction.php
- src/Core/Request/ProductDiscounts/ProductDiscountByKeyGetRequest.php
- src/Core/Request/ProductDiscounts/ProductDiscountDeleteByKeyRequest.php
- src/Core/Request/ProductDiscounts/ProductDiscountUpdateByKeyRequest.php
- tests/integration/ProductDiscount/ProductDiscountQueryRequestTest.php
- tests/integration/ProductDiscount/ProductDiscountUpdateRequestTest.php
> feat(ProductDiscount): support key attribute

- .travis.yml
- phpcs.xml
Adds prettyci as a codestyle checker
> Add Prettyci

- .travis.yml
- src/Core/Client/ClientFactory.php
> feat(ClientFactory): add option to inject middleware to HttpClients

- src/Core/Model/ApiClient/ApiClient.php
> feat(ApiClient): add deleteAt to feldDefinition method

- src/Core/Request/InStores/InStoreRequests.php
> Support store in shippingmethods #508

- tests/integration/ApiClient/ApiClientTest.php
> test to add check on deleteAt and deleteDayAfterCreation in ApiClient

- .gitignore
- src/Core/Model/Common/Resource.php
- tests/fixtures/FixtureException.php
- tests/integration/ApiTestCase.php
- tests/integration/CartDiscount/CartDiscountCreateRequestTest.php
- tests/integration/CartDiscount/CartDiscountFixture.php
- tests/integration/CartDiscount/CartDiscountQueryRequestTest.php
- tests/integration/CartDiscount/CartDiscountUpdateRequestTest.php
- tests/integration/Category/CategoryCreateRequestTest.php
- tests/integration/Category/CategoryFixture.php
- tests/integration/Category/CategoryQueryRequestTest.php
- tests/integration/Category/CategoryUpdateRequestTest.php
- tests/integration/ResourceFixture.php
> Migrate Category and CartDiscounts

- tests/integration/CartDiscount/CartDiscountCreateRequestTest.php
- tests/integration/CartDiscount/CartDiscountUpdateRequestTest.php
- tests/integration/State/StateFixture.php
- tests/integration/State/StateQueryRequestTest.php
- tests/integration/State/StateUpdateRequestTest.php
- tests/integration/Store/StoreDeleteRequestTest.php
- tests/integration/Store/StoreFixture.php
- tests/integration/Store/StoreQueryRequestTest.php
- tests/integration/Store/StoreUpdateRequestTest.php
>  Store and State integration test refactor

- tests/integration/CartDiscount/CartDiscountCreateRequestTest.php
- tests/integration/CartDiscount/CartDiscountQueryRequestTest.php
- tests/integration/CartDiscount/CartDiscountUpdateRequestTest.php
- tests/integration/TaxCategory/TaxCategoryFixture.php
- tests/integration/TaxCategory/TaxCategoryQueryRequestTest.php
- tests/integration/TaxCategory/TaxCategoryUpdateRequestTest.php
- tests/integration/Type/TypeFixture.php
- tests/integration/Type/TypeQueryRequestTest.php
- tests/integration/Type/TypeUpdateRequestTest.php
- tests/integration/Zone/ZoneFixture.php
- tests/integration/Zone/ZoneQueryRequestTest.php
- tests/integration/Zone/ZoneUpdateRequestTest.php
> TaxCategory Type Zone integration test refactor

- tests/integration/CartDiscount/CartDiscountUpdateRequestTest.php
- tests/integration/Category/CategoryUpdateRequestTest.php
- tests/integration/Channel/ChannelCreateRequestTest.php
- tests/integration/Channel/ChannelFixture.php
- tests/integration/Channel/ChannelQueryRequestTest.php
- tests/integration/Channel/ChannelUpdateRequestTest.php
- tests/integration/DiscountCode/DiscountCodeFixture.php
- tests/integration/DiscountCode/DiscountCodeQueryRequestTest.php
- tests/integration/DiscountCode/DiscountCodeUpdateRequestTest.php
- tests/integration/Type/TypeFixture.php
> Channel discountCode integration tests refactor

- tests/integration/CartDiscount/CartDiscountCreateRequestTest.php
- tests/integration/CartDiscount/CartDiscountFixture.php
- tests/integration/CartDiscount/CartDiscountQueryRequestTest.php
- tests/integration/CartDiscount/CartDiscountUpdateRequestTest.php
- tests/integration/Category/CategoryCreateRequestTest.php
- tests/integration/Category/CategoryFixture.php
- tests/integration/Category/CategoryQueryRequestTest.php
- tests/integration/Category/CategoryUpdateRequestTest.php
> Cart discount category integration tests refactoring

- tests/integration/Extension/ExtensionFixture.php
- tests/integration/Extension/ExtensionUpdateRequestTest.php
- tests/integration/GraphQL/GraphQLQueryTest.php
- tests/integration/Payment/PaymentFixture.php
- tests/integration/Payment/PaymentQueryRequestTest.php
- tests/integration/Payment/PaymentUpdateRequestTest.php
> Payment extension integration test refactor

- tests/integration/ApiTestCase.php
- tests/integration/DiscountCode/DiscountCodeUpdateRequestTest.php
- tests/integration/ResourceFixture.php
- tests/integration/ShippingMethod/ShippingMethodFixture.php
- tests/integration/ShippingMethod/ShippingMethodQueryRequestTest.php
- tests/integration/ShippingMethod/ShippingMethodUpdateRequestTest.php
- tests/integration/ShoppingList/ShoppingListFixture.php
- tests/integration/ShoppingList/ShoppingListQueryRequestTest.php
- tests/integration/ShoppingList/ShoppingListUpdateRequestTest.php
> Shopping list shipping method integration test refactor

- src/Core/Builder/Update/CustomersActionBuilder.php
- src/Core/Request/Customers/Command/CustomerAddStoreAction.php
- src/Core/Request/Customers/Command/CustomerRemoveStoreAction.php
- src/Core/Request/Customers/Command/CustomerSetStoresAction.php
- tests/integration/Customer/CustomerFixture.php
- tests/integration/Customer/CustomerUpdateRequestTest.php
> Add customer store action #534

- src/Core/Builder/Update/ShippingMethodsActionBuilder.php
- src/Core/Model/ShippingMethod/ShippingMethod.php
- src/Core/Model/ShippingMethod/ShippingMethodDraft.php
- src/Core/Request/ShippingMethods/Command/ShippingMethodSetDescriptionAction.php
- src/Core/Request/ShippingMethods/Command/ShippingMethodSetLocalizedDescriptionAction.php
- tests/integration/ShippingMethod/ShippingMethodUpdateRequestTest.php
- tests/unit/Model/RamlModelTest.php
> feat(ShippingMethods): add localized description to shippingMethods

- tests/integration/Cart/CartCreateRequestTest.php
- tests/integration/Cart/CartFixture.php
- tests/integration/Cart/CartQueryRequestTest.php
- tests/integration/Cart/CartTaxModeTest.php
- tests/integration/Cart/CartUpdateRequestTest.php
- tests/integration/CartDiscount/CartDiscountFixture.php
- tests/integration/Customer/CustomerFixture.php
- tests/integration/DiscountCode/DiscountCodeFixture.php
- tests/integration/GraphQL/GraphQLQueryTest.php
- tests/integration/ShippingMethod/ShippingMethodFixture.php
- tests/integration/ShoppingList/ShoppingListUpdateRequestTest.php
- tests/integration/TaxCategory/TaxCategoryUpdateRequestTest.php
- tests/integration/Zone/ZoneUpdateRequestTest.php
> Cart migrate integration tests

- src/Core/Builder/Update/OrdersActionBuilder.php
- src/Core/Model/Message/OrderStoreSetMessage.php
- src/Core/Request/Orders/Command/OrderSetStoreAction.php
- tests/integration/Order/OrderUpdateRequestTest.php
> add setStore action and message

- src/Core/Builder/Update/StoresActionBuilder.php
- src/Core/Model/Store/Store.php
- src/Core/Model/Store/StoreDraft.php
- src/Core/Request/PriceSelectTrait.php
- src/Core/Request/Stores/Command/StoreSetLanguagesAction.php
- tests/integration/Product/ProductQueryRequestTest.php
- tests/integration/Store/StoreUpdateRequestTest.php
> Add locale product projection

- tests/integration/Cart/CartCreateRequestTest.php
- tests/integration/Cart/CartTaxModeTest.php
- tests/integration/Cart/CartUpdateRequestTest.php
- tests/integration/Errors/ErrorResponseTest.php
- tests/integration/Product/ProductFixture.php
- tests/integration/Product/ProductQueryRequestTest.php
- tests/integration/Product/ProductUpdateRequestTest.php
- tests/integration/ShoppingList/ShoppingListUpdateRequestTest.php
> update all methods relative to Cart with Published Product

- .github/workflows/ci.yml
> GH workflows

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- install-apigen.sh
> Gh workflows docs

- .github/workflows/docs.yml
- README.md
- build/apigen.neon
- build/theme/overview.latte
- docroot/index.php
- src/Core/Client/ClientFactory.php
> Readme update

- src/Core/Model/Message/InventoryEntryQuantitySetMessage.php
> support InventoryEntryQuantitySet message

- src/Core/AbstractHttpClient.php
- tests/integration/Cart/CartFixture.php
- tests/integration/Customer/CustomerFixture.php
- tests/integration/Order/OrderFixture.php
- tests/integration/Order/OrderQueryRequestTest.php
- tests/integration/Order/OrderUpdateRequestTest.php
> Migrate order integration tests

- src/Core/Builder/Request/MeShoppingListRequestBuilder.php
- src/Core/Model/ShoppingList/MyShoppingListDraft.php
- src/Core/Request/Me/MeShoppingListByKeyGetRequest.php
- src/Core/Request/Me/MeShoppingListDeleteByKeyRequest.php
- src/Core/Request/Me/MeShoppingListUpdateByKeyRequest.php
- tests/integration/Me/MeShoppingListRequestTest.php
> Support me shoppinglist sdk

- src/Core/Error/LanguageUsedInStoresError.php
- tests/unit/Error/ApiErrorTest.php
> feat(Project): support language used in stores error

- .github/workflows/ci.yml
> chore(Github): fix release step

- src/Core/Client.php
- src/Core/Error/ApiException.php
- tests/unit/ClientTest.php
> Exception holds response body if available

- CHANGELOG.md
- package.json
- src/Core/Client/Adapter/AdapterFactory.php
- tests/integration/Cart/CartUpdateRequestTest.php
- tests/unit/Client/AdapterFactoryTest.php
> fix(Client): fix adapter factory to correctly identify the GuzzleAdapter

- src/Core/Builder/Update/StoresActionBuilder.php
- src/Core/Model/Store/Store.php
- src/Core/Model/Store/StoreDraft.php
- src/Core/Request/Stores/Command/StoreAddDistributionChannelAction.php
- src/Core/Request/Stores/Command/StoreAddSupplyChannelAction.php
- src/Core/Request/Stores/Command/StoreRemoveDistributionChannelAction.php
- src/Core/Request/Stores/Command/StoreRemoveSupplyChannelAction.php
- src/Core/Request/Stores/Command/StoreSetDistributionChannelsAction.php
- src/Core/Request/Stores/Command/StoreSetSupplyChannelsAction.php
- tests/integration/Store/StoreUpdateRequestTest.php
> support distribution and supply channel for update actions

- src/Core/Request/InStores/InStoreRequests.php
> Support cart replicate with store decorator

- src/Core/Model/Store/Store.php
- src/Core/Model/Store/StoreDraft.php
> Support custom fields for stores

- src/Core/Builder/Update/ShoppingListsActionBuilder.php
- src/Core/Model/ShoppingList/MyShoppingListDraft.php
- src/Core/Model/ShoppingList/ShoppingList.php
- src/Core/Model/ShoppingList/ShoppingListDraft.php
- src/Core/Request/InStores/InStoreRequests.php
- src/Core/Request/ShoppingLists/Command/ShoppingListSetStoreAction.php
- tests/integration/ShoppingList/ShoppingListUpdateRequestTest.php
> Add 'store' to \Commercetools\Core\Model\ShoppingList\ShoppingList

- tests/integration/Me/MeOrderRequestTest.php
- tests/integration/Order/OrderFixture.php
- tests/integration/Order/OrderUpdateRequestTest.php
- tests/integration/OrderEdit/OrderEditFixture.php
- tests/integration/OrderEdit/OrderEditQueryRequestTest.php
- tests/integration/OrderEdit/OrderEditUpdateRequestTest.php
- tests/integration/Type/TypeFixture.php
> test(OrderEdit): refactor order edit tests

- .github/workflows/ci.yml
- src/Core/Client/UserAgentProvider.php
- tests/integration/ApiTestCase.php
- tests/integration/ClientFactoryTest.php
> modify user agent

- src/Core/Builder/Update/ActionBuilder.php
- src/Core/Builder/Update/MeActionBuilder.php
- src/Core/Error/MissingRoleOnChannelError.php
- src/Core/Error/ProjectNotConfiguredForLanguagesError.php
- src/Core/Model/Cart/LineItem.php
- src/Core/Model/Cart/LineItemDraft.php
- src/Core/Model/Cart/MyLineItemDraft.php
- src/Core/Model/Message/CategorySlugChangedMessage.php
- src/Core/Model/Message/CustomerPasswordUpdatedMessage.php
- src/Core/Model/Message/ProductSlugChangedMessage.php
- src/Core/Request/Carts/Command/CartAddLineItemAction.php
- src/Core/Request/InStores/InStoreRequests.php
- src/Core/Request/Me/Command/MyCartAddLineItemAction.php
- src/Core/Request/OrderEdits/StagedOrder/Command/StagedOrderAddLineItemAction.php
- tests/integration/Cart/CartCreateRequestTest.php
- tests/integration/Cart/CartUpdateRequestTest.php
- tests/integration/Customer/CustomerLoginRequestTest.php
- tests/integration/Me/MeCartRequestTest.php
- tests/integration/Product/ProductUpdateRequestTest.php
- tests/integration/Project/ProjectGetRequestTest.php
- tests/unit/Model/RamlModelTest.php
- tests/unit/Request/GenericActionTest.php
- tests/unit/Request/Me/MeRequestTest.php
>  introduce more small features

- src/Core/Model/Message/OrderStateTransitionMessage.php
- src/Core/Model/Message/StoreCreatedMessage.php
- src/Core/Model/Message/StoreDeletedMessage.php
- tests/integration/Store/StoreDeleteRequestTest.php
> support oldState to OrderStateTransitionMessage and support store messages

- src/Core/Model/Subscription/ResourceDeletedDelivery.php
> Dataerasure to ResourceDeletedDelivery

- src/Core/Model/Message/ProductVariantAddedMessage.php
- tests/integration/Product/ProductUpdateRequestTest.php
> Product variant message

- src/Core/Builder/Request/CartRequestBuilder.php
- src/Core/Builder/Request/OrderRequestBuilder.php
- src/Core/Builder/Update/CartsActionBuilder.php
- src/Core/Model/Cart/Cart.php
- src/Core/Model/Cart/CartDraft.php
- src/Core/Request/Carts/CartByKeyGetRequest.php
- src/Core/Request/Carts/CartDeleteByKeyRequest.php
- src/Core/Request/Carts/CartUpdateByKeyRequest.php
- src/Core/Request/Carts/Command/CartSetKeyAction.php
- src/Core/Request/InStores/InStoreRequests.php
- src/Core/Request/Orders/OrderCreateFromCartRequest.php
- tests/integration/Cart/CartFixture.php
- tests/integration/Cart/CartQueryRequestTest.php
- tests/integration/Cart/CartUpdateRequestTest.php
- tests/integration/Me/MeOrderRequestTest.php
- tests/integration/Order/OrderQueryRequestTest.php
- tests/integration/Order/OrderUpdateRequestTest.php
- tests/unit/Request/Orders/OrderCreateFromCartRequestTest.php
> Support key in the cart

- tests/integration/Cart/CartCreateRequestTest.php
> add just test for Replicate cart store

- src/Core/Model/Customer/CustomerDraft.php
- src/Core/Request/Customers/CustomerLoginRequest.php
> Anonymous cart customer

- src/Core/Builder/Update/ShippingMethodsActionBuilder.php
- src/Core/Model/ShippingMethod/ShippingMethod.php
- src/Core/Model/ShippingMethod/ShippingMethodDraft.php
- src/Core/Request/ShippingMethods/Command/ShippingMethodSetCustomFieldAction.php
- src/Core/Request/ShippingMethods/Command/ShippingMethodSetCustomTypeAction.php
> Custom field in shippingMethod

- src/Core/Builder/Update/ProductSelectionsActionBuilder.php
- src/Core/Model/ApiClient/ApiClient.php
- src/Core/Model/ApiClient/ApiClientDraft.php
- src/Core/Model/Message/OrderPaymentAddedMessage.php
- src/Core/Model/ProductSelection/ProductSelection.php
- src/Core/Model/ProductSelection/ProductSelectionDraft.php
- src/Core/Request/ProductSelections/Command/ProductSelectionSetCustomFieldAction.php
- src/Core/Request/ProductSelections/Command/ProductSelectionSetCustomTypeAction.php
- src/Core/Request/ShippingMethods/ShippingMethodByMatchingLocationGetRequest.php
- tests/integration/Order/OrderQueryRequestTest.php
- tests/integration/Order/OrderUpdateRequestTest.php
- tests/integration/ProductSelection/ProductSelectionUpdateRequestTest.php
> PHP maintainance 

- src/Core/Builder/Update/StoresActionBuilder.php
- src/Core/Request/Stores/Command/StoreChangeProductSelectionAction.php
> add missing update action

- src/Core/Builder/Update/CustomersActionBuilder.php
- src/Core/Model/Customer/Customer.php
- src/Core/Model/Customer/CustomerDraft.php
- src/Core/Request/Customers/Command/CustomerSetAuthenticationModeAction.php
- tests/unit/Request/GenericActionTest.php
> Authentication mode customer

- src/Core/Model/Order/Order.php
- src/Core/Model/Store/Store.php
> updated some fields of the order and store to fix some tests that were failing

- CHANGELOG.md
- composer.json
- package.json
- src/Core/AbstractHttpClient.php
- src/Core/Model/Message/OrderReturnInfoSetMessage.php
- src/Core/Model/Message/OrderStoreSetMessage.php
- src/Core/Model/Message/ParcelItemsUpdatedMessage.php
- src/Core/Model/Message/PaymentStatusInterfaceCodeSetMessage.php
- src/Core/Model/Message/ProductDeletedMessage.php
- src/Core/Model/Message/ProductVariantDeletedMessage.php
- src/Core/Model/Message/ReviewStateTransitionMessage.php
- src/Core/Model/Message/StoreCreatedMessage.php
- tests/unit/Model/RamlModelTest.php
> Deprecation packagist and  fixed some errors

- README.md
> deprecate announcement
